package com.google.android.gms.internal.ads;

import android.content.Context;
import android.content.SharedPreferences;
import ch.qos.logback.classic.Level;
import ch.qos.logback.core.CoreConstants;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.json.JSONObject;

/* compiled from: com.google.android.gms:play-services-ads-lite@@20.1.0 */
/* loaded from: classes.dex */
public final class w3 {
    public static final o3<Boolean> A;
    public static final o3<Boolean> A0;
    public static final o3<Long> A1;
    public static final o3<Boolean> A2;
    public static final o3<Boolean> A3;
    public static final o3<String> A4;
    public static final o3<Boolean> A5;
    public static final o3<Integer> B;
    public static final o3<Boolean> B0;
    public static final o3<Boolean> B1;
    public static final o3<Boolean> B2;
    public static final o3<String> B3;
    public static final o3<Integer> B4;
    public static final o3<Boolean> B5;
    public static final o3<Long> C;
    public static final o3<Boolean> C0;
    public static final o3<Boolean> C1;
    public static final o3<Boolean> C2;
    public static final o3<Boolean> C3;
    public static final o3<Integer> C4;
    public static final o3<Boolean> C5;
    public static final o3<Boolean> D;
    public static final o3<Long> D0;
    public static final o3<Boolean> D1;
    public static final o3<Long> D2;
    public static final o3<Boolean> D3;
    public static final o3<Integer> D4;
    public static final o3<Boolean> D5;
    public static final o3<Boolean> E;
    public static final o3<Long> E0;
    public static final o3<Boolean> E1;
    public static final o3<Boolean> E2;
    public static final o3<Boolean> E3;
    public static final o3<Integer> E4;
    public static final o3<Boolean> E5;
    public static final o3<String> F;
    public static final o3<Boolean> F0;
    public static final o3<Boolean> F1;
    public static final o3<String> F2;
    public static final o3<Boolean> F3;
    public static final o3<String> F4;
    public static final o3<Boolean> F5;
    public static final o3<Integer> G;
    public static final o3<Long> G0;
    public static final o3<Boolean> G1;
    public static final o3<Integer> G2;
    public static final o3<Boolean> G3;
    public static final o3<String> G4;
    public static final o3<Boolean> G5;
    public static final o3<String> H;
    public static final o3<Boolean> H0;
    public static final o3<Boolean> H1;
    public static final o3<Boolean> H2;
    public static final o3<Integer> H3;
    public static final o3<String> H4;
    public static final o3<Boolean> H5;
    public static final o3<String> I;
    public static final o3<Long> I0;
    public static final o3<String> I1;
    public static final o3<Boolean> I2;
    public static final o3<Boolean> I3;
    public static final o3<String> I4;
    public static final o3<Boolean> I5;
    public static final o3<String> J;
    public static final o3<Boolean> J0;
    public static final o3<Boolean> J1;
    public static final o3<Boolean> J2;
    public static final o3<Boolean> J3;
    public static final o3<Integer> J4;
    public static final o3<Boolean> J5;
    public static final o3<String> K;
    public static final o3<Boolean> K0;
    public static final o3<Boolean> K1;
    public static final o3<Boolean> K2;
    public static final o3<Boolean> K3;
    public static final o3<String> K4;
    public static final o3<Integer> K5;
    public static final o3<Boolean> L;
    public static final o3<Boolean> L0;
    public static final o3<Boolean> L1;
    public static final o3<Boolean> L2;
    public static final o3<Boolean> L3;
    public static final o3<Integer> L4;
    public static final o3<Integer> L5;
    public static final o3<Boolean> M;
    public static final o3<Boolean> M0;
    public static final o3<Boolean> M1;
    public static final o3<Boolean> M2;
    public static final o3<String> M3;
    public static final o3<Integer> M4;
    public static final o3<Integer> M5;
    public static final o3<Integer> N;
    public static final o3<String> N0;
    public static final o3<Integer> N1;
    public static final o3<Boolean> N2;
    public static final o3<Integer> N3;
    public static final o3<Boolean> N4;
    public static final o3<Boolean> N5;
    public static final o3<Integer> O;
    public static final o3<String> O0;
    public static final o3<Boolean> O1;
    public static final o3<String> O2;
    public static final o3<Boolean> O3;
    public static final o3<Boolean> O4;
    public static final o3<Boolean> O5;
    public static final o3<Integer> P;
    public static final o3<Boolean> P0;
    public static final o3<Boolean> P1;
    public static final o3<Boolean> P2;
    public static final o3<Boolean> P3;
    public static final o3<Boolean> P4;
    public static final o3<Boolean> P5;
    public static final o3<String> Q;
    public static final o3<Long> Q0;
    public static final o3<Boolean> Q1;
    public static final o3<Long> Q2;
    public static final o3<Boolean> Q3;
    public static final o3<Boolean> Q4;
    public static final o3<String> Q5;
    public static final o3<String> R;
    public static final o3<Long> R0;
    public static final o3<Boolean> R1;
    public static final o3<String> R2;
    public static final o3<Boolean> R3;
    public static final o3<Boolean> R4;
    public static final o3<Integer> R5;
    public static final o3<Boolean> S;
    public static final o3<Boolean> S0;
    public static final o3<Boolean> S1;
    public static final o3<String> S2;
    public static final o3<Boolean> S3;
    public static final o3<String> S4;
    public static final o3<Integer> S5;
    public static final o3<Boolean> T;
    public static final o3<Boolean> T0;
    public static final o3<Boolean> T1;
    public static final o3<String> T2;
    public static final o3<Boolean> T3;
    public static final o3<Boolean> T4;
    public static final o3<Boolean> T5;
    public static final o3<Boolean> U;
    public static final o3<Boolean> U0;
    public static final o3<String> U1;
    public static final o3<String> U2;
    public static final o3<Boolean> U3;
    public static final o3<Boolean> U4;
    public static final o3<Float> U5;
    public static final o3<Boolean> V;
    public static final o3<Boolean> V0;
    public static final o3<String> V1;
    public static final o3<Integer> V2;
    public static final o3<Boolean> V3;
    public static final o3<Boolean> V4;
    public static final o3<Integer> V5;
    public static final o3<String> W;
    public static final o3<String> W0;
    public static final o3<Boolean> W1;
    public static final o3<Integer> W2;
    public static final o3<Boolean> W3;
    public static final o3<Boolean> W4;
    public static final o3<Integer> W5;
    public static final o3<String> X;
    public static final o3<Long> X0;
    public static final o3<String> X1;
    public static final o3<Boolean> X2;
    public static final o3<Boolean> X3;
    public static final o3<Integer> X4;
    public static final o3<Integer> X5;
    public static final o3<Boolean> Y;
    public static final o3<String> Y0;
    public static final o3<String> Y1;
    public static final o3<Boolean> Y2;
    public static final o3<Boolean> Y3;
    public static final o3<Integer> Y4;
    public static final o3<Boolean> Y5;
    public static final o3<String> Z;
    public static final o3<Boolean> Z0;
    public static final o3<Boolean> Z1;
    public static final o3<Boolean> Z2;
    public static final o3<Boolean> Z3;
    public static final o3<Boolean> Z4;
    public static final o3<Float> Z5;
    public static final o3<Long> a0;
    public static final o3<Boolean> a1;
    public static final o3<Integer> a2;
    public static final o3<Boolean> a3;
    public static final o3<Boolean> a4;
    public static final o3<Boolean> a5;
    public static final o3<Integer> a6;
    public static final o3<Integer> b0;
    public static final o3<Boolean> b1;
    public static final o3<Boolean> b2;
    public static final o3<Integer> b3;
    public static final o3<Boolean> b4;
    public static final o3<Boolean> b5;
    public static final o3<Integer> b6;
    public static final o3<Boolean> c0;
    public static final o3<Boolean> c1;
    public static final o3<String> c2;
    public static final o3<Boolean> c3;
    public static final o3<Long> c4;
    public static final o3<Boolean> c5;
    public static final o3<Integer> c6;
    public static final o3<Integer> d0;
    public static final o3<Integer> d1;
    public static final o3<Boolean> d2;
    public static final o3<Boolean> d3;
    public static final o3<Integer> d4;
    public static final o3<Integer> d5;
    public static final o3<Integer> d6;
    public static final o3<Boolean> e0;
    public static final o3<Boolean> e1;
    public static final o3<Boolean> e2;
    public static final o3<Boolean> e3;
    public static final o3<Integer> e4;
    public static final o3<Integer> e5;
    public static final o3<Boolean> e6;
    public static final o3<Boolean> f0;
    public static final o3<Boolean> f1;
    public static final o3<Boolean> f2;
    public static final o3<String> f3;
    public static final o3<Integer> f4;
    public static final o3<Boolean> f5;
    public static final o3<Boolean> f6;
    public static final o3<Boolean> g0;
    public static final o3<Integer> g1;
    public static final o3<Boolean> g2;
    public static final o3<String> g3;
    public static final o3<Integer> g4;
    public static final o3<Boolean> g5;
    public static final o3<Integer> g6;
    public static final o3<Boolean> h0;
    public static final o3<Long> h1;
    public static final o3<Boolean> h2;
    public static final o3<Integer> h3;
    public static final o3<Boolean> h4;
    public static final o3<String> h5;
    public static final o3<Integer> h6;
    public static final o3<Boolean> i0;
    public static final o3<Long> i1;
    public static final o3<Boolean> i2;
    public static final o3<Boolean> i3;
    public static final o3<Boolean> i4;
    public static final o3<Integer> i5;
    public static final o3<String> i6;
    public static final o3<Boolean> j0;
    public static final o3<Boolean> j1;
    public static final o3<Boolean> j2;
    public static final o3<Integer> j3;
    public static final o3<Boolean> j4;
    public static final o3<Boolean> j5;
    public static final o3<Boolean> k0;
    public static final o3<Boolean> k1;
    public static final o3<Boolean> k2;
    public static final o3<Boolean> k3;
    public static final o3<String> k4;
    public static final o3<Integer> k5;
    public static final o3<Boolean> l0;
    public static final o3<Boolean> l1;
    public static final o3<Boolean> l2;
    public static final o3<Boolean> l3;
    public static final o3<Boolean> l4;
    public static final o3<Integer> l5;
    public static final o3<Long> m0;
    public static final o3<Boolean> m1;
    public static final o3<Long> m2;
    public static final o3<Boolean> m3;
    public static final o3<Integer> m4;
    public static final o3<Boolean> m5;
    public static final o3<Boolean> n;
    public static final o3<String> n0;
    public static final o3<Boolean> n1;
    public static final o3<Long> n2;
    public static final o3<Boolean> n3;
    public static final o3<Boolean> n4;
    public static final o3<Boolean> n5;
    public static final o3<Boolean> o;
    public static final o3<Boolean> o0;
    public static final o3<Boolean> o1;
    public static final o3<Integer> o2;
    public static final o3<Boolean> o3;
    public static final o3<Boolean> o4;
    public static final o3<Boolean> o5;
    public static final o3<Boolean> p;
    public static final o3<Boolean> p0;
    public static final o3<Boolean> p1;
    public static final o3<Integer> p2;
    public static final o3<Boolean> p3;
    public static final o3<Integer> p4;
    public static final o3<Boolean> p5;
    public static final o3<Integer> q;
    public static final o3<String> q0;
    public static final o3<Boolean> q1;
    public static final o3<Boolean> q2;
    public static final o3<Boolean> q3;
    public static final o3<Boolean> q4;
    public static final o3<Boolean> q5;
    public static final o3<Integer> r;
    public static final o3<Boolean> r0;
    public static final o3<Integer> r1;
    public static final o3<Long> r2;
    public static final o3<String> r3;
    public static final o3<Boolean> r4;
    public static final o3<String> r5;
    public static final o3<Integer> s;
    public static final o3<Boolean> s0;
    public static final o3<Boolean> s1;
    public static final o3<Boolean> s2;
    public static final o3<Boolean> s3;
    public static final o3<Boolean> s4;
    public static final o3<Boolean> s5;
    public static final o3<Long> t;
    public static final o3<Boolean> t0;
    public static final o3<Boolean> t1;
    public static final o3<Boolean> t2;
    public static final o3<Integer> t3;
    public static final o3<Boolean> t4;
    public static final o3<Boolean> t5;
    public static final o3<Long> u;
    public static final o3<Integer> u0;
    public static final o3<Boolean> u1;
    public static final o3<Boolean> u2;
    public static final o3<Integer> u3;
    public static final o3<Boolean> u4;
    public static final o3<Integer> u5;
    public static final o3<Integer> v;
    public static final o3<Boolean> v0;
    public static final o3<Boolean> v1;
    public static final o3<Long> v2;
    public static final o3<Boolean> v3;
    public static final o3<Integer> v4;
    public static final o3<Boolean> v5;
    public static final o3<String> w;
    public static final o3<Boolean> w0;
    public static final o3<String> w1;
    public static final o3<Boolean> w2;
    public static final o3<String> w3;
    public static final o3<Integer> w4;
    public static final o3<Boolean> w5;
    public static final o3<Long> x;
    public static final o3<Boolean> x0;
    public static final o3<Boolean> x1;
    public static final o3<Boolean> x2;
    public static final o3<Boolean> x3;
    public static final o3<String> x4;
    public static final o3<Boolean> x5;
    public static final o3<Boolean> y;
    public static final o3<Boolean> y0;
    public static final z4<Boolean> y1;
    public static final o3<Long> y2;
    public static final o3<String> y3;
    public static final o3<String> y4;
    public static final o3<Integer> y5;
    public static final o3<Long> z;
    public static final o3<String> z0;
    public static final o3<Boolean> z1;
    public static final o3<Long> z2;
    public static final o3<Boolean> z3;
    public static final o3<String> z4;
    public static final o3<Integer> z5;
    public static final o3<String> a = o3.k(1, "gads:sdk_core_location:client:html", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html");

    /* renamed from: b, reason: collision with root package name */
    public static final o3<String> f9862b = o3.k(1, "gads:active_view_location:html", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html");

    /* renamed from: c, reason: collision with root package name */
    public static final z4<Boolean> f9863c = o5.f7902d;

    /* renamed from: d, reason: collision with root package name */
    public static final o3<Integer> f9864d = o3.h(1, "gads:http_url_connection_factory:timeout_millis", 10000);

    /* renamed from: e, reason: collision with root package name */
    public static final o3<String> f9865e = o3.k(1, "gads:video_exo_player:version", "3");

    /* renamed from: f, reason: collision with root package name */
    public static final o3<Integer> f9866f = o3.h(1, "gads:video_exo_player:connect_timeout", 8000);

    /* renamed from: g, reason: collision with root package name */
    public static final o3<Integer> f9867g = o3.h(1, "gads:video_exo_player:read_timeout", 8000);

    /* renamed from: h, reason: collision with root package name */
    public static final o3<Integer> f9868h = o3.h(1, "gads:video_exo_player:loading_check_interval", 1048576);

    /* renamed from: i, reason: collision with root package name */
    public static final o3<Integer> f9869i = o3.h(1, "gads:video_exo_player:exo_player_precache_limit", Integer.MAX_VALUE);

    /* renamed from: j, reason: collision with root package name */
    public static final o3<Integer> f9870j = o3.h(1, "gads:video_exo_player:byte_buffer_precache_limit", Integer.MAX_VALUE);

    /* renamed from: k, reason: collision with root package name */
    public static final o3<Integer> f9871k = o3.h(1, "gads:video_exo_player_socket_receive_buffer_size", 0);

    /* renamed from: l, reason: collision with root package name */
    public static final o3<String> f9872l = o3.k(1, "gads:video_exo_player:precache_exceptions", "");

    /* renamed from: m, reason: collision with root package name */
    public static final o3<Integer> f9873m = o3.h(1, "gads:video_exo_player:min_retry_count", -1);

    static {
        Boolean bool = Boolean.TRUE;
        n = new j3(1, "gads:video_exo_player:fmp4_extractor_enabled", bool);
        Boolean bool2 = Boolean.FALSE;
        o = new j3(1, "gads:video_exo_player:use_play_back_info_for_should_start_play_back", bool2);
        p = new j3(1, "gads:video_exo_player:treat_load_exception_as_non_fatal", bool2);
        q = o3.h(1, "gads:video_stream_cache:limit_count", 5);
        r = o3.h(1, "gads:video_stream_cache:limit_space", 8388608);
        s = o3.h(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
        t = o3.i(1, "gads:video_stream_cache:limit_time_sec", 300L);
        u = o3.i(1, "gads:video_stream_cache:notify_interval_millis", 125L);
        v = o3.h(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
        w = o3.k(1, "gads:video:metric_frame_hash_times", "");
        x = o3.i(1, "gads:video:metric_frame_hash_time_leniency", 500L);
        y = new j3(1, "gads:video:force_watermark", bool2);
        z = o3.i(1, "gads:video:surface_update_min_spacing_ms", 1000L);
        A = new j3(1, "gads:video:spinner:enabled", bool2);
        B = o3.h(1, "gads:video:spinner:scale", 4);
        C = o3.i(1, "gads:video:spinner:jank_threshold_ms", 50L);
        D = new j3(1, "gads:video:aggressive_media_codec_release", bool2);
        E = new j3(1, "gads:memory_bundle:debug_info", bool2);
        F = o3.k(1, "gads:video:codec_query_mime_types", "");
        G = o3.h(1, "gads:video:codec_query_minimum_version", 16);
        H = o3.k(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_banner.js");
        I = o3.k(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_expanded_banner.js");
        J = o3.k(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_interstitial.js");
        K = o3.k(1, "gad:mraid:version", "3.0");
        L = new j3(1, "gads:mraid:expanded_interstitial_fix", bool2);
        M = new j3(1, "gads:mraid:initial_size_fallback", bool2);
        N = o3.h(1, "gads:content_vertical_fingerprint_number", 100);
        O = o3.h(1, "gads:content_vertical_fingerprint_bits", 23);
        P = o3.h(1, "gads:content_vertical_fingerprint_ngram", 3);
        Q = o3.k(1, "gads:content_fetch_view_tag_id", "googlebot");
        R = o3.k(1, "gads:content_fetch_exclude_view_tag", "none");
        S = new j3(1, "gads:content_fetch_disable_get_title_from_webview", bool2);
        T = new j3(1, "gads:content_fetch_enable_new_content_score", bool2);
        U = new j3(1, "gads:content_fetch_enable_serve_once", bool2);
        V = new j3(1, "gads:sai:enabled", bool);
        W = o3.k(1, "gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
        X = o3.k(1, "gads:sai:impression_ping_schema_v2", "^[^?]*(/adview|/pcs/view).*");
        Y = new j3(1, "gads:sai:using_macro:enabled", bool2);
        Z = o3.k(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
        a0 = o3.i(1, "gads:sai:timeout_ms", -1L);
        b0 = o3.h(1, "gads:sai:scion_thread_pool_size", 5);
        c0 = new j3(1, "gads:sai:app_measurement_enabled3", bool2);
        d0 = o3.h(1, "gads:sai:app_measurement_min_client_dynamite_version", 20290);
        e0 = new j3(1, "gads:sai:force_through_reflection", bool);
        f0 = new j3(1, "gads:sai:gmscore_availability_check_disabled", bool2);
        g0 = new j3(1, "gads:sai:logging_disabled_for_drx", bool2);
        h0 = new j3(1, "gads:sai:app_measurement_npa_enabled", bool2);
        i0 = new j3(1, "gads:idless:idless_disables_attestation", bool);
        j0 = new j3(1, "gads:idless:app_measurement_idless_enabled", bool);
        k0 = new j3(1, "gads:sai:server_side_npa:disable_writing", bool2);
        l0 = new j3(1, "gads:sai:server_side_npa:enabled", bool2);
        m0 = o3.i(1, "gads:sai:server_side_npa:ttl", TimeUnit.DAYS.toMillis(90L));
        n0 = o3.k(1, "gads:sai:server_side_npa:shared_preference_key_list", "{  \"__default__\": [    \"IABTCF_TCString\"  ],  \"mobileads_consent\": [    \"consent_string\"  ]}");
        o0 = new j3(1, "gads:idless:internal_state_enabled", bool);
        p0 = new j3(1, "gads:idless:idless_disables_offline_ads_signalling", bool);
        q0 = o3.k(1, "gads:idless:cookie_modification", "=; Max-Age=-1; path=/; domain=.doubleclick.net");
        r0 = new j3(1, "gads:interstitial:app_must_be_foreground:enabled", bool2);
        s0 = new j3(1, "gads:interstitial:foreground_report:enabled", bool2);
        t0 = new j3(1, "gads:interstitial:default_immersive", bool2);
        u0 = o3.h(1, "gads:show_interstitial_with_context:min_version", 999999999);
        v0 = new j3(1, "gads:webview:error_web_response:enabled", bool2);
        w0 = new j3(1, "gads:webview:set_fixed_text_zoom", bool2);
        x0 = new j3(1, "gads:webviewgone:kill_process:enabled", bool2);
        y0 = new j3(1, "gads:webviewgone:new_onshow:enabled", bool2);
        z0 = o3.k(1, "gads:webview_cookie_url", "googleads.g.doubleclick.net");
        A0 = new j3(1, "gads:new_rewarded_ad:enabled", bool);
        B0 = new j3(1, "gads:rewarded:adapter_initialization_enabled", bool2);
        C0 = new j3(1, "gads:rewarded:ad_metadata_enabled", bool2);
        D0 = o3.i(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500L);
        E0 = o3.i(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5L));
        F0 = new j3(1, "gads:adid_values_in_adrequest:enabled", bool2);
        G0 = o3.i(1, "gads:adid_values_in_adrequest:timeout", 2000L);
        H0 = new j3(1, "gads:disable_adid_values_in_ms", bool2);
        I0 = o3.i(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000L);
        J0 = new j3(1, "gads:custom_close_blocking:enabled", bool2);
        K0 = new j3(1, "gads:disabling_closable_area:enabled", bool2);
        L0 = new j3(1, "gads:use_system_ui_for_fullscreen:enabled", bool2);
        M0 = new j3(1, "gads:ad_overlay:collect_cutout_info:enabled", bool2);
        N0 = o3.k(1, "gads:spherical_video:vertex_shader", "");
        O0 = o3.k(1, "gads:spherical_video:fragment_shader", "");
        P0 = new j3(1, "gads:include_local_global_rectangles", bool2);
        Q0 = o3.i(1, "gads:position_watcher:throttle_ms", 200L);
        R0 = o3.i(1, "gads:position_watcher:scroll_aware_throttle_ms", 33L);
        S0 = new j3(1, "gads:position_watcher:enable_scroll_aware_ads", bool2);
        T0 = new j3(1, "gads:position_watcher:send_scroll_data", bool2);
        U0 = new j3(1, "gads:gen204_signals:enabled", bool2);
        V0 = new j3(1, "gads:extra_sdk_versions_for_crash_reports:enabled", bool);
        W0 = o3.k(1, "gads:logged_adapter_version_classes", "");
        X0 = o3.i(1, "gads:rtb_v1_1:signal_timeout_ms", 1000L);
        Y0 = o3.k(1, "gads:rtb_logging:regex", "(?!)");
        Z0 = new j3(1, "gads:presentation_error:urls_enabled", bool);
        a1 = new j3(1, "gads:rtb_interstitial:use_fullscreen_monitor", bool);
        b1 = new j3(1, "gads:native_required_assets:enabled", bool2);
        c1 = new j3(1, "gads:native_required_assets:check_inner_mediaview:enabled", bool);
        d1 = o3.h(1, "gads:native_ad_options_rtb:min_version", 999999999);
        e1 = new j3(1, "gads:track_view_next_runloop:enabled", bool2);
        f1 = new j3(1, "gads:native_required_assets:viewability:enabled", bool2);
        g1 = o3.h(1, "gads:adapter_initialization:min_sdk_version", 15301000);
        h1 = o3.i(1, "gads:adapter_initialization:timeout", 30L);
        i1 = o3.i(1, "gads:adapter_initialization:cld_timeout", 10L);
        j1 = new j3(1, "gads:additional_video_csi:enabled", bool2);
        k1 = new j3(1, "gads:csi:enabled_per_sampling", bool2);
        l1 = new j3(1, "gads:always_set_transfer_listener:enabled", bool2);
        m1 = new j3(1, "gads:initialization_csi:enabled", bool2);
        n1 = new j3(1, "gads:msa:experiments:enabled", bool2);
        o1 = new j3(1, "gads:msa:experiments:ps:enabled", bool2);
        p1 = new j3(1, "gads:msa:experiments:fb:enabled", bool);
        q1 = new j3(1, "gads:msa:experiments:ps:er", bool);
        r1 = o3.h(1, "gads:gestures:a2:enabled", 0);
        s1 = new j3(1, "gads:msa:experiments:a2", bool2);
        t1 = new j3(1, "gads:msa:experiments:log", bool);
        u1 = new j3(1, "gads:msa:experiments:vfb", bool);
        v1 = new j3(1, "gads:msa:experiments:incapi:enabled", bool2);
        w1 = o3.k(1, "gads:msa:experiments:incapi:trusted_cert", "308204433082032ba003020102020900c2e08746644a308d300d06092a864886f70d01010405003074310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e205669657731143012060355040a130b476f6f676c6520496e632e3110300e060355040b1307416e64726f69643110300e06035504031307416e64726f6964301e170d3038303832313233313333345a170d3336303130373233313333345a3074310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e205669657731143012060355040a130b476f6f676c6520496e632e3110300e060355040b1307416e64726f69643110300e06035504031307416e64726f696430820120300d06092a864886f70d01010105000382010d00308201080282010100ab562e00d83ba208ae0a966f124e29da11f2ab56d08f58e2cca91303e9b754d372f640a71b1dcb130967624e4656a7776a92193db2e5bfb724a91e77188b0e6a47a43b33d9609b77183145ccdf7b2e586674c9e1565b1f4c6a5955bff251a63dabf9c55c27222252e875e4f8154a645f897168c0b1bfc612eabf785769bb34aa7984dc7e2ea2764cae8307d8c17154d7ee5f64a51a44a602c249054157dc02cd5f5c0e55fbef8519fbe327f0b1511692c5a06f19d18385f5c4dbc2d6b93f68cc2979c70e18ab93866b3bd5db8999552a0e3b4c99df58fb918bedc182ba35e003c1b4b10dd244a8ee24fffd333872ab5221985edab0fc0d0b145b6aa192858e79020103a381d93081d6301d0603551d0e04160414c77d8cc2211756259a7fd382df6be398e4d786a53081a60603551d2304819e30819b8014c77d8cc2211756259a7fd382df6be398e4d786a5a178a4763074310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e205669657731143012060355040a130b476f6f676c6520496e632e3110300e060355040b1307416e64726f69643110300e06035504031307416e64726f6964820900c2e08746644a308d300c0603551d13040530030101ff300d06092a864886f70d010104050003820101006dd252ceef85302c360aaace939bcff2cca904bb5d7a1661f8ae46b2994204d0ff4a68c7ed1a531ec4595a623ce60763b167297a7ae35712c407f208f0cb109429124d7b106219c084ca3eb3f9ad5fb871ef92269a8be28bf16d44c8d9a08e6cb2f005bb3fe2cb96447e868e731076ad45b33f6009ea19c161e62641aa99271dfd5228c5c587875ddb7f452758d661f6cc0cccb7352e424cc4365c523532f7325137593c4ae341f4db41edda0d0b1071a7c440f0fe9ea01cb627ca674369d084bd2fd911ff06cdbf2cfa10dc0f893ae35762919048c7efc64c7144178342f70581c9de573af55b390dd7fdb9418631895d5f759f30112687ff621410c069308a");
        x1 = new j3(1, "gads:gestures:clearTd:enabled", bool2);
        y1 = n5.f7655b;
        z1 = new j3(1, "gads:gestures:errorlogging:enabled", bool2);
        A1 = o3.i(1, "gads:gestures:task_timeout", 2000L);
        B1 = new j3(1, "gads:gestures:asig:enabled", bool2);
        C1 = new j3(1, "gads:gestures:ans:enabled", bool2);
        D1 = new j3(1, "gads:gestures:tos:enabled", bool2);
        E1 = new j3(1, "gads:gestures:brt:enabled", bool);
        F1 = new j3(1, "gads:gestures:fpi:enabled", bool2);
        G1 = new j3(1, "gads:signal:app_permissions:disabled", bool2);
        H1 = new j3(1, "gads:gestures:hpk:enabled", bool);
        I1 = o3.k(1, "gads:gestures:pk", "");
        J1 = new j3(1, "gads:gestures:bs:enabled", bool);
        K1 = new j3(1, "gads:gestures:check_initialization_thread:enabled", bool2);
        L1 = new j3(1, "gads:gestures:init_new_thread:enabled", bool);
        M1 = new j3(1, "gads:gestures:pds:enabled", bool);
        N1 = o3.h(1, "gads:gestures:as2percentage", 0);
        O1 = new j3(1, "gads:gestures:ns:enabled", bool);
        P1 = new j3(1, "gads:gestures:vdd:enabled", bool2);
        Q1 = new j3(1, "gads:native:asset_view_touch_events", bool2);
        R1 = new j3(1, "gads:native:set_touch_listener_on_asset_views", bool);
        S1 = new j3(1, "gads:ais:enabled", bool);
        T1 = new j3(1, "gads:stav:enabled", bool2);
        U1 = o3.l(1, "gads:sdk_core_constants:experiment_id");
        V1 = o3.k(1, "gads:sdk_core_constants:caps", "");
        W1 = new j3(1, "gads:js_flags:disable_phenotype", bool2);
        X1 = o3.k(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
        Y1 = o3.k(1, "gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
        Z1 = new j3(1, "gads:native:get_native_ad_view_signals", bool2);
        a2 = o3.h(1, "gads:native_video_load_timeout", 10);
        b2 = new j3(1, "gads:omid:native_video_ad_user_action_event:enabled", bool2);
        c2 = o3.k(1, "gads:ad_choices_content_description", "Ad Choices Icon");
        d2 = new j3(1, "gads:enable_singleton_broadcast_receiver", bool2);
        e2 = new j3(1, "gads:native:media_view_match_parent:enabled", bool2);
        f2 = new j3(1, "gads:video:restrict_inside_web_view:enabled", bool2);
        g2 = new j3(1, "gads:native:count_impression_for_assets", bool2);
        h2 = new j3(1, "gads:fluid_ad:use_wrap_content_height", bool2);
        i2 = new j3(1, "gads:rtb_v1_1:fetch_app_settings_using_cld:enabled", bool);
        j2 = new j3(1, "gads:get_request_signals_cld:enabled", bool);
        k2 = new j3(1, "gads:get_request_signals_common_cld:enabled", bool2);
        l2 = new j3(1, "gads:rtb_v1_1:use_manifest_appid_cld:enabled", bool);
        m2 = o3.i(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000L);
        n2 = o3.i(1, "gads:parental_controls:timeout", 2000L);
        o2 = o3.h(1, "gads:cache:ad_request_timeout_millis", 250);
        p2 = o3.h(1, "gads:cache:max_concurrent_downloads", 10);
        q2 = new j3(1, "gads:cache:downloader_use_high_priority", bool2);
        r2 = o3.i(1, "gads:cache:javascript_timeout_millis", 5000L);
        s2 = new j3(1, "gads:cache:bind_on_foreground", bool2);
        t2 = new j3(1, "gads:cache:bind_on_init", bool2);
        u2 = new j3(1, "gads:cache:bind_on_request", bool2);
        v2 = o3.i(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30L));
        w2 = new j3(1, "gads:cache:use_cache_data_source", bool2);
        x2 = new j3(1, "gads:cache:connection_per_read", bool2);
        y2 = o3.i(1, "gads:cache:connection_timeout", 5000L);
        z2 = o3.i(1, "gads:cache:read_only_connection_timeout", 5000L);
        A2 = new j3(1, "gads:cache:read_inner_data_source_if_gcache_miss", bool2);
        B2 = new j3(1, "gads:cache:read_inner_data_source_if_gcache_not_downloaded", bool2);
        C2 = new j3(1, "gads:cache:function_call_timeout_v1:enabled", bool2);
        D2 = o3.i(1, "gads:cache:function_call_timeout", 5000L);
        E2 = new j3(1, "gads:http_assets_cache:enabled", bool2);
        F2 = o3.k(1, "gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
        G2 = o3.h(1, "gads:http_assets_cache:time_out", 100);
        H2 = new j3(1, "gads:chrome_custom_tabs_browser:enabled", bool2);
        I2 = new j3(1, "gads:chrome_custom_tabs:disabled", bool2);
        J2 = new j3(1, "gads:chrome_custom_tabs_browser_v2:enabled", bool2);
        K2 = new j3(1, "gads:cct_v2_connection:enabled", bool2);
        L2 = new j3(1, "gads:cct_v2_direct_launch:enabled", bool2);
        M2 = new j3(1, "gads:chrome_custom_tabs_for_native_ads:enabled", bool2);
        N2 = new j3(1, "gad:cct_v2_beta:enabled", bool2);
        O2 = o3.k(1, "gad:publisher_testing:cct_v2:enabled_list", "");
        P2 = new j3(2, "CHROME_CUSTOM_TAB_OPT_OUT", bool2);
        Q2 = o3.i(1, "gads:debug_hold_gesture:time_millis", 2000L);
        R2 = o3.k(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
        S2 = o3.k(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
        T2 = o3.k(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
        U2 = o3.k(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
        V2 = o3.h(1, "gads:drx_debug:timeout_ms", Level.TRACE_INT);
        W2 = o3.h(1, "gad:pixel_dp_comparision_multiplier", 1);
        X2 = new j3(1, "gad:interstitial_notify_publisher_without_delay", bool2);
        Y2 = new j3(1, "gad:interstitial_for_multi_window", bool2);
        Z2 = new j3(1, "gad:interstitial_ad_stay_active_in_multi_window", bool2);
        a3 = new j3(1, "gad:interstitial_multi_window_method", bool2);
        b3 = o3.h(1, "gad:interstitial:close_button_padding_dip", 0);
        c3 = new j3(1, "gads:clearcut_logging:enabled", bool2);
        d3 = new j3(1, "gads:clearcut_logging:write_to_file", bool2);
        e3 = new j3(1, "gad:publisher_testing:force_local_request:enabled", bool);
        f3 = o3.k(1, "gad:publisher_testing:force_local_request:enabled_list", "");
        g3 = o3.k(1, "gad:publisher_testing:force_local_request:disabled_list", "");
        h3 = o3.h(1, "gad:http_redirect_max_count:times", 8);
        i3 = new j3(1, "gads:omid:enabled", bool);
        j3 = o3.h(1, "gads:omid:destroy_webview_delay", CoreConstants.MILLIS_IN_ONE_SECOND);
        k3 = new j3(1, "gads:omid_1_3_activate:enabled", bool2);
        l3 = new j3(1, "gads:omid_1_3_create_html_session:enabled", bool2);
        m3 = o3.g(1, "gads:omid_1_3_create_js_session:enabled", bool2);
        n3 = o3.g(1, "gads:omid_1_3_friendly_obstruction:enabled", bool2);
        o3 = o3.g(1, "gads:omid_1_3_fire_loaded_event:enabled", bool2);
        p3 = o3.g(1, "gads:omid_use_admob_impl_dependency:enabled", bool2);
        q3 = o3.g(1, "gads:nonagon:banner:enabled", bool);
        r3 = o3.k(1, "gads:nonagon:banner:ad_unit_exclusions", "(?!)");
        s3 = o3.g(1, "gads:nonagon:app_open:enabled", bool);
        t3 = o3.h(1, "gads:app_open_beta:min_version", 999999999);
        u3 = o3.h(1, "gads:app_open_ad_open_beta_api:min_version", 202490999);
        v3 = o3.g(1, "gads:nonagon:app_open_app_switch_signal:enabled", bool2);
        w3 = o3.k(1, "gads:nonagon:app_open:ad_unit_exclusions", "(?!)");
        x3 = o3.g(1, "gads:nonagon:interstitial:enabled", bool);
        y3 = o3.k(1, "gads:nonagon:interstitial:ad_unit_exclusions", "(?!)");
        z3 = o3.g(1, "gads:nonagon:rewardedvideo:enabled", bool);
        A3 = o3.g(1, "gads:nonagon:mobile_ads_setting_manager:enabled", bool);
        B3 = o3.k(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)");
        C3 = o3.g(1, "gads:nonagon:banner:check_dp_size", bool);
        D3 = o3.g(1, "gads:nonagon:rewarded:load_multiple_ads", bool);
        E3 = o3.g(1, "gads:nonagon:return_no_fill_error_code", bool2);
        F3 = o3.g(1, "gads:nonagon:continue_on_no_fill", bool2);
        G3 = o3.g(1, "gads:nonagon:separate_timeout:enabled", bool);
        H3 = o3.h(1, "gads:nonagon:request_timeout:seconds", 60);
        I3 = o3.g(1, "gads:nonagon:banner_recursive_renderer", bool2);
        J3 = o3.g(1, "gads:nonagon:app_stats_lock:enabled", bool2);
        K3 = o3.g(1, "gads:nonagon:app_stats_main_thread:enabled", bool2);
        L3 = o3.g(1, "gads:uri_query_to_map_bg_thread:enabled", bool2);
        M3 = o3.k(1, "gads:uri_query_to_map_bg_thread:types", "/result");
        N3 = o3.h(1, "gads:uri_query_to_map_bg_thread:min_length", CoreConstants.MILLIS_IN_ONE_SECOND);
        O3 = o3.g(1, "gads:nonagon:active_view_gmsg_background_thread:enabled", bool);
        P3 = o3.g(1, "gads:active_view_gmsg_separate_pool:enabled", bool);
        Q3 = o3.g(1, "gads:signals:ad_id_info:enabled", bool2);
        R3 = o3.g(1, "gads:signals:app_index:enabled", bool2);
        S3 = o3.g(1, "gads:signals:attestation_token:enabled", bool2);
        T3 = o3.g(1, "gads:signals:cache:enabled", bool2);
        U3 = o3.g(1, "gads:signals:doritos:enabled", bool2);
        V3 = o3.g(1, "gads:signals:doritos:v1:enabled", bool2);
        W3 = o3.g(1, "gads:signals:doritos:v2:immediate:enabled", bool2);
        X3 = o3.g(1, "gads:signals:parental_control:enabled", bool2);
        Y3 = o3.g(1, "gads:signals:video_decoder:enabled", bool2);
        Z3 = o3.g(1, "gads:signals:banner_hardware_acceleration:enabled", bool2);
        a4 = o3.g(1, "gads:signals:native_hardware_acceleration:enabled", bool2);
        b4 = o3.g(1, "gads:attestation_token:enabled", bool2);
        c4 = o3.i(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000L);
        d4 = o3.h(1, "gads:adoverlay:b68684796:targeting_sdk:lower_bound", 27);
        e4 = o3.h(1, "gads:adoverlay:b68684796:targeting_sdk:upper_bound", 26);
        f4 = o3.h(1, "gads:adoverlay:b68684796:sdk_int:lower_bound", 27);
        g4 = o3.h(1, "gads:adoverlay:b68684796:sdk_int:upper_bound", 26);
        h4 = o3.g(1, "gads:consent:shared_preference_reading:enabled", bool);
        i4 = o3.g(1, "gads:consent:iab_consent_info:enabled", bool);
        j4 = o3.g(1, "gads:fc_consent:shared_preference_reading:enabled", bool);
        k4 = o3.k(1, "gads:sp:json_string", "");
        l4 = o3.g(1, "gads:nativeads:image:sample:enabled", bool);
        m4 = o3.h(1, "gads:nativeads:image:sample:pixels", 1048576);
        n4 = o3.g(1, "gads:nativeads:pub_image_scale_type:enabled", bool);
        o4 = o3.g(1, "gads:offline_signaling:enabled", bool2);
        p4 = o3.h(1, "gads:offline_signaling:log_maximum", 100);
        q4 = o3.g(1, "gads:nativeads:template_signal:enabled", bool);
        r4 = o3.g(1, "gads:nativeads:media_content_aspect_ratio:enabled", bool);
        s4 = o3.g(1, "gads:nativeads:media_content_metadata:enabled", bool);
        t4 = o3.g(1, "gads:predictive_prefetch_from_cld:enabled", bool2);
        u4 = o3.g(1, "gads:precache_pool:verbose_logging", bool2);
        v4 = o3.h(1, "gads:rewarded_precache_pool:count", 0);
        w4 = o3.h(1, "gads:interstitial_precache_pool:count", 0);
        x4 = o3.k(1, "gads:rewarded_precache_pool:discard_strategy", "lru");
        y4 = o3.k(1, "gads:interstitial_precache_pool:discard_strategy", "lru");
        z4 = o3.k(1, "gads:rewarded_precache_pool:cache_start_trigger", "onAdClosed");
        A4 = o3.k(1, "gads:interstitial_precache_pool:cache_start_trigger", "onAdClosed");
        B4 = o3.h(1, "gads:rewarded_precache_pool:size", 1);
        C4 = o3.h(1, "gads:interstitial_precache_pool:size", 1);
        D4 = o3.h(1, "gads:rewarded_precache_pool:ad_time_limit", 1200);
        E4 = o3.h(1, "gads:interstitial_precache_pool:ad_time_limit", 1200);
        F4 = o3.k(1, "gads:rewarded_precache_pool:schema", "customTargeting,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
        G4 = o3.k(1, "gads:interstitial_precache_pool:schema", "customTargeting,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
        H4 = o3.k(1, "gads:app_open_precache_pool:schema", "orientation,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
        I4 = o3.k(1, "gads:app_open_precache_pool:discard_strategy", "oldest");
        J4 = o3.h(1, "gads:app_open_precache_pool:count", 0);
        K4 = o3.k(1, "gads:app_open_precache_pool:cache_start_trigger", "onAdClosed");
        L4 = o3.h(1, "gads:app_open_precache_pool:size", 1);
        M4 = o3.h(1, "gads:app_open_precache_pool:ad_time_limit", 14400);
        N4 = o3.g(1, "gads:memory_leak:b129558083", bool2);
        O4 = o3.g(1, "gads:unhandled_event_reporting:enabled", bool2);
        P4 = o3.g(1, "gads:response_info:enabled", bool);
        Q4 = o3.g(1, "gads:csi:interstitial_failed_to_show:enabled", bool2);
        R4 = o3.g(1, "gads:csi:mediation_failure:enabled", bool2);
        S4 = o3.k(1, "gads:csi:error_parsing:regex", "^(\\d+)");
        T4 = o3.g(1, "gads:csi:eids_from_cld:enabled", bool2);
        U4 = o3.g(1, "gads:request_id_check:enabled", bool2);
        V4 = o3.g(1, "gads:request_id_int32:enabled", bool);
        W4 = o3.g(1, "gads:signal_collection_without_rendering:enabled", bool);
        X4 = o3.h(1, "gads:native_ads_signal:timeout", CoreConstants.MILLIS_IN_ONE_SECOND);
        Y4 = o3.h(1, "gads:signal_v2:min_version", 19677000);
        Z4 = o3.g(2, "DISABLE_CRASH_REPORTING", bool2);
        a5 = o3.g(1, "gads:paid_event_listener:enabled", bool);
        b5 = o3.g(1, "gads:interscroller_ad:enabled", bool);
        c5 = o3.g(1, "gads:interscroller_ad:refresh:enabled", bool2);
        d5 = o3.h(1, "gads:interscroller:min_width", 300);
        e5 = o3.h(1, "gads:interscroller:min_height", 250);
        f5 = o3.g(1, "gads:is_in_scroll_view_new_api:enabled", bool);
        g5 = o3.g(1, "gads:policy_validator_for_all_pubs:enabled", bool2);
        h5 = o3.k(1, "gad:publisher_testing:policy_validator:enabled_list", "");
        i5 = o3.h(1, "gads:policy_validator_layoutparam:flags", 808);
        j5 = o3.g(2, "NATIVE_AD_DEBUGGER_ENABLED", bool);
        k5 = o3.h(1, "gads:policy_validator_overlay_width:dp", 350);
        l5 = o3.h(1, "gads:policy_validator_overlay_height:dp", 140);
        m5 = o3.g(1, "gads:use_wide_viewport:enabled", bool2);
        n5 = o3.g(1, "gads:load_with_overview_mode:enabled", bool2);
        o5 = o3.g(1, "gads:wire_banner_listener_after_request:enabled", bool2);
        p5 = o3.g(1, "gads:wire_app_open_listener_after_request:enabled", bool2);
        q5 = o3.g(1, "gads:wire_interstitial_listener_after_request:enabled", bool2);
        r5 = o3.k(1, "gads:server_transaction_source:list", "Network");
        s5 = o3.g(1, "gads:can_open_app_and_open_app_action:enabled", bool2);
        t5 = o3.g(1, "gads:open_gmsg:set_uri_data_and_type:enabled", bool2);
        u5 = o3.h(1, "gads:ad_error_api:min_version", 202006000);
        v5 = o3.g(1, "gads:forward_bow_error_string:enabled", bool);
        w5 = o3.g(1, "gads:continue_on_process_response:enabled", bool2);
        x5 = o3.g(1, "gads:mediation_status_reporting:enabled", bool);
        y5 = o3.h(1, "gads:mediation_no_fill_error:min_version", 999999999);
        z5 = o3.h(1, "gads:offline_database_version:version", 1);
        A5 = o3.g(1, "gads:offline_ads_notification:enabled", bool);
        B5 = o3.g(1, "gads:use_new_network_api:enabled", bool);
        C5 = o3.g(1, "gads:handle_click_recorded_event:enabled", bool2);
        D5 = o3.g(1, "gads:default_network_type_fine_to_unknown:enabled", bool);
        E5 = o3.g(1, "gads:handle_intent_async:enabled", bool2);
        F5 = o3.g(1, "gads:skip_deep_link_validation_native_ads:enabled", bool2);
        G5 = o3.g(1, "gads:try_deep_link_fallback_native_ads:enabled", bool2);
        H5 = o3.g(1, "gads:in_app_link_handling_for_android_11_enabled:enabled", bool2);
        I5 = o3.g(1, "gads:new_remote_logging_utils:enabled", bool2);
        J5 = o3.g(1, "gads:remote_logging:enabled", bool2);
        K5 = o3.h(1, "gads:remote_log_send_rate_ms", CoreConstants.MILLIS_IN_ONE_MINUTE);
        L5 = o3.h(1, "gads:remote_log_queue_max_entries", 500);
        M5 = o3.h(1, "gads:app_event_queue_size", 20);
        N5 = o3.g(1, "gads:hide_grey_title_bar:enabled", bool2);
        O5 = o3.g(1, "gads:interstitial_ad_parameter_handler:enabled", bool2);
        P5 = o3.g(1, "gads:inspector:enabled", bool);
        Q5 = o3.k(1, "gads:inspector:ui_url", "https://admob-gmats.uc.r.appspot.com/");
        R5 = o3.h(1, "gads:inspector:max_ad_life_cycles", CoreConstants.MILLIS_IN_ONE_SECOND);
        S5 = o3.h(1, "gads:inspector:ui_invocation_millis", 2000);
        T5 = o3.g(1, "gads:inspector:shake_enabled", bool);
        U5 = o3.j(1, "gads:inspector:shake_strength", 2.0f);
        V5 = o3.h(1, "gads:inspector:shake_interval", 500);
        W5 = o3.h(1, "gads:inspector:shake_reset_time_ms", 3000);
        X5 = o3.h(1, "gads:inspector:shake_count", 3);
        Y5 = o3.g(1, "gads:inspector:flick_enabled", bool);
        Z5 = o3.j(1, "gads:inspector:flick_rotation_threshold", 45.0f);
        a6 = o3.h(1, "gads:inspector:flick_reset_time_ms", 3000);
        b6 = o3.h(1, "gads:inspector:flick_count", 2);
        c6 = o3.h(1, "gads:inspector:icon_width_px", 256);
        d6 = o3.h(1, "gads:inspector:icon_height_px", 256);
        e6 = o3.g(1, "gads:paw_register_webview:enabled", bool);
        f6 = o3.g(1, "gads:h5ads:enabled", bool);
        g6 = o3.h(1, "gads:h5ads:max_num_ad_objects", 10);
        h6 = o3.h(1, "gads:h5ads:max_gmsg_length", Level.TRACE_INT);
        i6 = o3.k(1, "gads:h5ads:afma_prefix", "(window.AFMA_ReceiveMessage || window.h5_iframe.contentWindow.AFMA_ReceiveMessage || function() {})");
    }

    public static void a(final Context context) {
        y3.a(new p12(context) { // from class: com.google.android.gms.internal.ads.v3
            private final Context a;

            {
                this.a = context;
            }

            @Override // com.google.android.gms.internal.ads.p12
            public final Object zza() {
                Context context2 = this.a;
                o3<String> o3Var = w3.a;
                c.c().a(context2);
                return null;
            }
        });
    }

    public static void b(Context context, int i7, JSONObject jSONObject) {
        c.a();
        SharedPreferences.Editor editorEdit = q3.a(context).edit();
        c.b();
        z4<Boolean> z4Var = d5.a;
        c.b().c(editorEdit, 1, jSONObject);
        c.a();
        editorEdit.commit();
    }

    public static List<String> c() {
        return c.b().d();
    }

    public static List<String> d() {
        return c.b().e();
    }
}